/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/single': RouteRecordInfo<'/single', '/single', Record<never, never>, Record<never, never>>,
    '/single/modal-a': RouteRecordInfo<'/single/modal-a', '/single/modal-a', Record<never, never>, Record<never, never>>,
    '/single/modal-b': RouteRecordInfo<'/single/modal-b', '/single/modal-b', Record<never, never>, Record<never, never>>,
    '/single/modal-b/child': RouteRecordInfo<'/single/modal-b/child', '/single/modal-b/child', Record<never, never>, Record<never, never>>,
  }
}
